CREATE TABLE IF NOT EXISTS managers (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    nip VARCHAR(15) NOT NULL UNIQUE,
    status VARCHAR(15) NOT NULL,
    contact_id INTEGER REFERENCES contacts(id),
    position_id INT NULL,
    department_id INT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);